---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "blockchain-paper-network"

version: 1.0.0

client:
  organization: Org1
  connection:
    timeout:
      peer:
        endorser: '300'

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        # Add your peer's TLS CA certificate here
        -----END CERTIFICATE-----
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com
      hostnameOverride: peer0.org1.example.com

certificateAuthorities:
  ca.org1.example.com:
    url: http://localhost:7054
    caName: ca-org1
    tlsCACerts:
      pem: |
        -----BEGIN CERTIFICATE-----
        # Add your CA's TLS certificate here
        -----END CERTIFICATE-----
    httpOptions:
      verify: false

channels:
  mychannel:
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true