name: "fabric-network"
version: "1.0"

channels:
  thesischannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  Org1:
    mspid: Org1MSP
    peers:
      - peer0.org1.example.com
    certificateAuthorities:
      - ca.org1.example.com

  OrdererOrg:
    mspid: OrdererMSP
    orderers:
      - orderer.example.com

orderers:
  orderer.example.com:
    url: grpcs://localhost:7050
    tlsCACerts:
      path: ../organizations/ordererOrganizations/example.com/tlsca/tlsca.example.com-cert.pem
    grpcOptions:
      ssl-target-name-override: orderer.example.com

peers:
  peer0.org1.example.com:
    url: grpcs://localhost:7051
    tlsCACerts:
      path: ../organizations/peerOrganizations/org1.example.com/tlsca/tlsca.org1.example.com-cert.pem
    grpcOptions:
      ssl-target-name-override: peer0.org1.example.com

certificateAuthorities:
  ca.org1.example.com:
    url: https://localhost:7054
    caName: ca.org1.example.com
    tlsCACerts:
      path: ../organizations/fabric-ca/org1/tls-cert.pem
    httpOptions:
      verify: false